// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Stack;

/************************************************************/
/**
 * 
 */
public class Person {
	/**
	 * 
	 */
	public String name;
	
	public Person(String name) {
		this.name=name;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	
};
