// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Stack;

/************************************************************/
/**
 * 
 */
public class Stack {
	/**
	 * 
	 */
	private int size;
	/**
	 * 
	 */
	private StackEl top;
	
	
	public Stack() {
		this.size=0;
		this.top=null;
	}

	/**
	 * 
	 * @return 
	 */
	public int getSize() {
		return size;
	}

	/**
	 * 
	 * @param p 
	 */
	public void push(Person p) {
		StackEl stackEl = new StackEl(p);
		stackEl.setPrecedingEl(this.top);
		this.setTop(stackEl);
	}

	/**
	 * 
	 * @return 
	 */
	public Person pop() {
		Person p = this.top.getContent();
		this.setTop(this.top.getPrecedingEl());
		return p;
	}

	/**
	 * 
	 * @return 
	 */
	public boolean isEmpty() {
		return this.size==0;
	}

	/**
	 * 
	 * @param setTop 
	 */
	private void setTop(StackEl setTop) {
		this.top=setTop;
	}
};
