/**
 */
package es.unirioja.uml2prov.xtend.prov;

import javax.xml.namespace.QName;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.EMap;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Document Root</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtendCode.prov.DocumentRoot#getMixed <em>Mixed</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getXMLNSPrefixMap <em>XMLNS Prefix Map</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getXSISchemaLocation <em>XSI Schema Location</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getActedOnBehalfOf <em>Acted On Behalf Of</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getActivity <em>Activity</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getAgent <em>Agent</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getAlternateOf <em>Alternate Of</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getBundle <em>Bundle</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getCollection <em>Collection</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getDocument <em>Document</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getEmptyCollection <em>Empty Collection</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getHadMember <em>Had Member</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getHadPrimarySource <em>Had Primary Source</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getEntity <em>Entity</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getInternalElement <em>Internal Element</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getLabel <em>Label</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getLocation <em>Location</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getOrganization <em>Organization</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getOther <em>Other</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getPerson <em>Person</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getPlan <em>Plan</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getRole <em>Role</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getSoftwareAgent <em>Software Agent</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getSpecializationOf <em>Specialization Of</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getType <em>Type</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getUsed <em>Used</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getValue <em>Value</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getWasAssociatedWith <em>Was Associated With</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getWasAttributedTo <em>Was Attributed To</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getWasDerivedFrom <em>Was Derived From</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getWasEndedBy <em>Was Ended By</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getWasGeneratedBy <em>Was Generated By</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getWasInfluencedBy <em>Was Influenced By</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getWasInformedBy <em>Was Informed By</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getWasInvalidatedBy <em>Was Invalidated By</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getWasQuotedFrom <em>Was Quoted From</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getWasRevisionOf <em>Was Revision Of</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getWasStartedBy <em>Was Started By</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getId <em>Id</em>}</li>
 *   <li>{@link xtendCode.prov.DocumentRoot#getRef <em>Ref</em>}</li>
 * </ul>
 *
 * @see xtendCode.prov.ProvPackage#getDocumentRoot()
 * @model extendedMetaData="name='' kind='mixed'"
 * @generated
 */
public interface DocumentRoot extends EObject {
	/**
	 * Returns the value of the '<em><b>Mixed</b></em>' attribute list.
	 * The list contents are of type {@link org.eclipse.emf.ecore.util.FeatureMap.Entry}.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Mixed</em>' attribute list isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Mixed</em>' attribute list.
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_Mixed()
	 * @model unique="false" dataType="org.eclipse.emf.ecore.EFeatureMapEntry" many="true"
	 *        extendedMetaData="kind='elementWildcard' name=':mixed'"
	 * @generated
	 */
	FeatureMap getMixed();

	/**
	 * Returns the value of the '<em><b>XMLNS Prefix Map</b></em>' map.
	 * The key is of type {@link java.lang.String},
	 * and the value is of type {@link java.lang.String},
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>XMLNS Prefix Map</em>' map isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>XMLNS Prefix Map</em>' map.
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_XMLNSPrefixMap()
	 * @model mapType="org.eclipse.emf.ecore.EStringToStringMapEntry&lt;org.eclipse.emf.ecore.EString, org.eclipse.emf.ecore.EString&gt;" transient="true"
	 *        extendedMetaData="kind='attribute' name='xmlns:prefix'"
	 * @generated
	 */
	EMap<String, String> getXMLNSPrefixMap();

	/**
	 * Returns the value of the '<em><b>XSI Schema Location</b></em>' map.
	 * The key is of type {@link java.lang.String},
	 * and the value is of type {@link java.lang.String},
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>XSI Schema Location</em>' map isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>XSI Schema Location</em>' map.
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_XSISchemaLocation()
	 * @model mapType="org.eclipse.emf.ecore.EStringToStringMapEntry&lt;org.eclipse.emf.ecore.EString, org.eclipse.emf.ecore.EString&gt;" transient="true"
	 *        extendedMetaData="kind='attribute' name='xsi:schemaLocation'"
	 * @generated
	 */
	EMap<String, String> getXSISchemaLocation();

	/**
	 * Returns the value of the '<em><b>Acted On Behalf Of</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Acted On Behalf Of</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Acted On Behalf Of</em>' containment reference.
	 * @see #setActedOnBehalfOf(Delegation)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_ActedOnBehalfOf()
	 * @model containment="true" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='actedOnBehalfOf' namespace='##targetNamespace'"
	 * @generated
	 */
	Delegation getActedOnBehalfOf();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getActedOnBehalfOf <em>Acted On Behalf Of</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Acted On Behalf Of</em>' containment reference.
	 * @see #getActedOnBehalfOf()
	 * @generated
	 */
	void setActedOnBehalfOf(Delegation value);

	/**
	 * Returns the value of the '<em><b>Activity</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Activity</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Activity</em>' containment reference.
	 * @see #setActivity(Activity)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_Activity()
	 * @model containment="true" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='activity' namespace='##targetNamespace'"
	 * @generated
	 */
	Activity getActivity();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getActivity <em>Activity</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Activity</em>' containment reference.
	 * @see #getActivity()
	 * @generated
	 */
	void setActivity(Activity value);

	/**
	 * Returns the value of the '<em><b>Agent</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Agent</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Agent</em>' containment reference.
	 * @see #setAgent(Agent)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_Agent()
	 * @model containment="true" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='agent' namespace='##targetNamespace'"
	 * @generated
	 */
	Agent getAgent();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getAgent <em>Agent</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Agent</em>' containment reference.
	 * @see #getAgent()
	 * @generated
	 */
	void setAgent(Agent value);

	/**
	 * Returns the value of the '<em><b>Alternate Of</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Alternate Of</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Alternate Of</em>' containment reference.
	 * @see #setAlternateOf(Alternate)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_AlternateOf()
	 * @model containment="true" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='alternateOf' namespace='##targetNamespace'"
	 * @generated
	 */
	Alternate getAlternateOf();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getAlternateOf <em>Alternate Of</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Alternate Of</em>' containment reference.
	 * @see #getAlternateOf()
	 * @generated
	 */
	void setAlternateOf(Alternate value);

	/**
	 * Returns the value of the '<em><b>Bundle</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Bundle</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Bundle</em>' containment reference.
	 * @see #setBundle(Bundle)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_Bundle()
	 * @model containment="true" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='bundle' namespace='##targetNamespace'"
	 * @generated
	 */
	Bundle getBundle();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getBundle <em>Bundle</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Bundle</em>' containment reference.
	 * @see #getBundle()
	 * @generated
	 */
	void setBundle(Bundle value);

	/**
	 * Returns the value of the '<em><b>Collection</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Collection</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Collection</em>' containment reference.
	 * @see #setCollection(Collection)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_Collection()
	 * @model containment="true" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='collection' namespace='##targetNamespace'"
	 * @generated
	 */
	Collection getCollection();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getCollection <em>Collection</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Collection</em>' containment reference.
	 * @see #getCollection()
	 * @generated
	 */
	void setCollection(Collection value);

	/**
	 * Returns the value of the '<em><b>Document</b></em>' containment reference list.
	 * The list contents are of type {@link xtendCode.prov.Document}.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Document</em>' containment reference list isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Document</em>' containment reference list.
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_Document()
	 * @model containment="true" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='document' namespace='##targetNamespace'"
	 * @generated
	 */
	EList<Document> getDocument();

	/**
	 * Returns the value of the '<em><b>Empty Collection</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Empty Collection</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Empty Collection</em>' containment reference.
	 * @see #setEmptyCollection(EmptyCollection)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_EmptyCollection()
	 * @model containment="true" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='emptyCollection' namespace='##targetNamespace'"
	 * @generated
	 */
	EmptyCollection getEmptyCollection();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getEmptyCollection <em>Empty Collection</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Empty Collection</em>' containment reference.
	 * @see #getEmptyCollection()
	 * @generated
	 */
	void setEmptyCollection(EmptyCollection value);

	/**
	 * Returns the value of the '<em><b>Had Member</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Had Member</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Had Member</em>' containment reference.
	 * @see #setHadMember(Membership)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_HadMember()
	 * @model containment="true" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='hadMember' namespace='##targetNamespace'"
	 * @generated
	 */
	Membership getHadMember();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getHadMember <em>Had Member</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Had Member</em>' containment reference.
	 * @see #getHadMember()
	 * @generated
	 */
	void setHadMember(Membership value);

	/**
	 * Returns the value of the '<em><b>Had Primary Source</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Had Primary Source</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Had Primary Source</em>' containment reference.
	 * @see #setHadPrimarySource(PrimarySource)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_HadPrimarySource()
	 * @model containment="true" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='hadPrimarySource' namespace='##targetNamespace'"
	 * @generated
	 */
	PrimarySource getHadPrimarySource();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getHadPrimarySource <em>Had Primary Source</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Had Primary Source</em>' containment reference.
	 * @see #getHadPrimarySource()
	 * @generated
	 */
	void setHadPrimarySource(PrimarySource value);

	/**
	 * Returns the value of the '<em><b>Entity</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Entity</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Entity</em>' containment reference.
	 * @see #setEntity(Entity)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_Entity()
	 * @model containment="true" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='entity' namespace='##targetNamespace'"
	 * @generated
	 */
	Entity getEntity();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getEntity <em>Entity</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Entity</em>' containment reference.
	 * @see #getEntity()
	 * @generated
	 */
	void setEntity(Entity value);

	/**
	 * Returns the value of the '<em><b>Internal Element</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Internal Element</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Internal Element</em>' containment reference.
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_InternalElement()
	 * @model containment="true" upper="-2" transient="true" changeable="false" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='internalElement' namespace='##targetNamespace'"
	 * @generated
	 */
	EObject getInternalElement();

	/**
	 * Returns the value of the '<em><b>Label</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Label</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Label</em>' containment reference.
	 * @see #setLabel(InternationalizedString)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_Label()
	 * @model containment="true" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='label' namespace='##targetNamespace'"
	 * @generated
	 */
	InternationalizedString getLabel();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getLabel <em>Label</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Label</em>' containment reference.
	 * @see #getLabel()
	 * @generated
	 */
	void setLabel(InternationalizedString value);

	/**
	 * Returns the value of the '<em><b>Location</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Location</em>' attribute isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Location</em>' attribute.
	 * @see #setLocation(Object)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_Location()
	 * @model unique="false" dataType="org.eclipse.emf.ecore.xml.type.AnySimpleType" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='location' namespace='##targetNamespace'"
	 * @generated
	 */
	Object getLocation();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getLocation <em>Location</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Location</em>' attribute.
	 * @see #getLocation()
	 * @generated
	 */
	void setLocation(Object value);

	/**
	 * Returns the value of the '<em><b>Organization</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Organization</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Organization</em>' containment reference.
	 * @see #setOrganization(Organization)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_Organization()
	 * @model containment="true" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='organization' namespace='##targetNamespace'"
	 * @generated
	 */
	Organization getOrganization();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getOrganization <em>Organization</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Organization</em>' containment reference.
	 * @see #getOrganization()
	 * @generated
	 */
	void setOrganization(Organization value);

	/**
	 * Returns the value of the '<em><b>Other</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Other</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Other</em>' containment reference.
	 * @see #setOther(Other)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_Other()
	 * @model containment="true" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='other' namespace='##targetNamespace'"
	 * @generated
	 */
	Other getOther();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getOther <em>Other</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Other</em>' containment reference.
	 * @see #getOther()
	 * @generated
	 */
	void setOther(Other value);

	/**
	 * Returns the value of the '<em><b>Person</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Person</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Person</em>' containment reference.
	 * @see #setPerson(Person)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_Person()
	 * @model containment="true" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='person' namespace='##targetNamespace'"
	 * @generated
	 */
	Person getPerson();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getPerson <em>Person</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Person</em>' containment reference.
	 * @see #getPerson()
	 * @generated
	 */
	void setPerson(Person value);

	/**
	 * Returns the value of the '<em><b>Plan</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Plan</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Plan</em>' containment reference.
	 * @see #setPlan(Plan)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_Plan()
	 * @model containment="true" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='plan' namespace='##targetNamespace'"
	 * @generated
	 */
	Plan getPlan();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getPlan <em>Plan</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Plan</em>' containment reference.
	 * @see #getPlan()
	 * @generated
	 */
	void setPlan(Plan value);

	/**
	 * Returns the value of the '<em><b>Role</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Role</em>' attribute isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Role</em>' attribute.
	 * @see #setRole(Object)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_Role()
	 * @model unique="false" dataType="org.eclipse.emf.ecore.xml.type.AnySimpleType" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='role' namespace='##targetNamespace'"
	 * @generated
	 */
	Object getRole();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getRole <em>Role</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Role</em>' attribute.
	 * @see #getRole()
	 * @generated
	 */
	void setRole(Object value);

	/**
	 * Returns the value of the '<em><b>Software Agent</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Software Agent</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Software Agent</em>' containment reference.
	 * @see #setSoftwareAgent(SoftwareAgent)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_SoftwareAgent()
	 * @model containment="true" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='softwareAgent' namespace='##targetNamespace'"
	 * @generated
	 */
	SoftwareAgent getSoftwareAgent();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getSoftwareAgent <em>Software Agent</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Software Agent</em>' containment reference.
	 * @see #getSoftwareAgent()
	 * @generated
	 */
	void setSoftwareAgent(SoftwareAgent value);

	/**
	 * Returns the value of the '<em><b>Specialization Of</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Specialization Of</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Specialization Of</em>' containment reference.
	 * @see #setSpecializationOf(Specialization)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_SpecializationOf()
	 * @model containment="true" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='specializationOf' namespace='##targetNamespace'"
	 * @generated
	 */
	Specialization getSpecializationOf();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getSpecializationOf <em>Specialization Of</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Specialization Of</em>' containment reference.
	 * @see #getSpecializationOf()
	 * @generated
	 */
	void setSpecializationOf(Specialization value);

	/**
	 * Returns the value of the '<em><b>Type</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Type</em>' attribute isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Type</em>' attribute.
	 * @see #setType(Object)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_Type()
	 * @model unique="false" dataType="org.eclipse.emf.ecore.xml.type.AnySimpleType" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='type' namespace='##targetNamespace'"
	 * @generated
	 */
	Object getType();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getType <em>Type</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Type</em>' attribute.
	 * @see #getType()
	 * @generated
	 */
	void setType(Object value);

	/**
	 * Returns the value of the '<em><b>Used</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Used</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Used</em>' containment reference.
	 * @see #setUsed(Usage)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_Used()
	 * @model containment="true" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='used' namespace='##targetNamespace'"
	 * @generated
	 */
	Usage getUsed();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getUsed <em>Used</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Used</em>' containment reference.
	 * @see #getUsed()
	 * @generated
	 */
	void setUsed(Usage value);

	/**
	 * Returns the value of the '<em><b>Value</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Value</em>' attribute isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Value</em>' attribute.
	 * @see #setValue(Object)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_Value()
	 * @model unique="false" dataType="org.eclipse.emf.ecore.xml.type.AnySimpleType" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='value' namespace='##targetNamespace'"
	 * @generated
	 */
	Object getValue();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getValue <em>Value</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Value</em>' attribute.
	 * @see #getValue()
	 * @generated
	 */
	void setValue(Object value);

	/**
	 * Returns the value of the '<em><b>Was Associated With</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Was Associated With</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Was Associated With</em>' containment reference.
	 * @see #setWasAssociatedWith(Association)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_WasAssociatedWith()
	 * @model containment="true" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='wasAssociatedWith' namespace='##targetNamespace'"
	 * @generated
	 */
	Association getWasAssociatedWith();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getWasAssociatedWith <em>Was Associated With</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Was Associated With</em>' containment reference.
	 * @see #getWasAssociatedWith()
	 * @generated
	 */
	void setWasAssociatedWith(Association value);

	/**
	 * Returns the value of the '<em><b>Was Attributed To</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Was Attributed To</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Was Attributed To</em>' containment reference.
	 * @see #setWasAttributedTo(Attribution)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_WasAttributedTo()
	 * @model containment="true" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='wasAttributedTo' namespace='##targetNamespace'"
	 * @generated
	 */
	Attribution getWasAttributedTo();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getWasAttributedTo <em>Was Attributed To</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Was Attributed To</em>' containment reference.
	 * @see #getWasAttributedTo()
	 * @generated
	 */
	void setWasAttributedTo(Attribution value);

	/**
	 * Returns the value of the '<em><b>Was Derived From</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Was Derived From</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Was Derived From</em>' containment reference.
	 * @see #setWasDerivedFrom(Derivation)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_WasDerivedFrom()
	 * @model containment="true" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='wasDerivedFrom' namespace='##targetNamespace'"
	 * @generated
	 */
	Derivation getWasDerivedFrom();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getWasDerivedFrom <em>Was Derived From</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Was Derived From</em>' containment reference.
	 * @see #getWasDerivedFrom()
	 * @generated
	 */
	void setWasDerivedFrom(Derivation value);

	/**
	 * Returns the value of the '<em><b>Was Ended By</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Was Ended By</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Was Ended By</em>' containment reference.
	 * @see #setWasEndedBy(End)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_WasEndedBy()
	 * @model containment="true" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='wasEndedBy' namespace='##targetNamespace'"
	 * @generated
	 */
	End getWasEndedBy();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getWasEndedBy <em>Was Ended By</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Was Ended By</em>' containment reference.
	 * @see #getWasEndedBy()
	 * @generated
	 */
	void setWasEndedBy(End value);

	/**
	 * Returns the value of the '<em><b>Was Generated By</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Was Generated By</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Was Generated By</em>' containment reference.
	 * @see #setWasGeneratedBy(Generation)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_WasGeneratedBy()
	 * @model containment="true" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='wasGeneratedBy' namespace='##targetNamespace'"
	 * @generated
	 */
	Generation getWasGeneratedBy();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getWasGeneratedBy <em>Was Generated By</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Was Generated By</em>' containment reference.
	 * @see #getWasGeneratedBy()
	 * @generated
	 */
	void setWasGeneratedBy(Generation value);

	/**
	 * Returns the value of the '<em><b>Was Influenced By</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Was Influenced By</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Was Influenced By</em>' containment reference.
	 * @see #setWasInfluencedBy(Influence)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_WasInfluencedBy()
	 * @model containment="true" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='wasInfluencedBy' namespace='##targetNamespace'"
	 * @generated
	 */
	Influence getWasInfluencedBy();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getWasInfluencedBy <em>Was Influenced By</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Was Influenced By</em>' containment reference.
	 * @see #getWasInfluencedBy()
	 * @generated
	 */
	void setWasInfluencedBy(Influence value);

	/**
	 * Returns the value of the '<em><b>Was Informed By</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Was Informed By</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Was Informed By</em>' containment reference.
	 * @see #setWasInformedBy(Communication)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_WasInformedBy()
	 * @model containment="true" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='wasInformedBy' namespace='##targetNamespace'"
	 * @generated
	 */
	Communication getWasInformedBy();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getWasInformedBy <em>Was Informed By</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Was Informed By</em>' containment reference.
	 * @see #getWasInformedBy()
	 * @generated
	 */
	void setWasInformedBy(Communication value);

	/**
	 * Returns the value of the '<em><b>Was Invalidated By</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Was Invalidated By</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Was Invalidated By</em>' containment reference.
	 * @see #setWasInvalidatedBy(Invalidation)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_WasInvalidatedBy()
	 * @model containment="true" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='wasInvalidatedBy' namespace='##targetNamespace'"
	 * @generated
	 */
	Invalidation getWasInvalidatedBy();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getWasInvalidatedBy <em>Was Invalidated By</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Was Invalidated By</em>' containment reference.
	 * @see #getWasInvalidatedBy()
	 * @generated
	 */
	void setWasInvalidatedBy(Invalidation value);

	/**
	 * Returns the value of the '<em><b>Was Quoted From</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Was Quoted From</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Was Quoted From</em>' containment reference.
	 * @see #setWasQuotedFrom(Quotation)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_WasQuotedFrom()
	 * @model containment="true" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='wasQuotedFrom' namespace='##targetNamespace'"
	 * @generated
	 */
	Quotation getWasQuotedFrom();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getWasQuotedFrom <em>Was Quoted From</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Was Quoted From</em>' containment reference.
	 * @see #getWasQuotedFrom()
	 * @generated
	 */
	void setWasQuotedFrom(Quotation value);

	/**
	 * Returns the value of the '<em><b>Was Revision Of</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Was Revision Of</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Was Revision Of</em>' containment reference.
	 * @see #setWasRevisionOf(Revision)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_WasRevisionOf()
	 * @model containment="true" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='wasRevisionOf' namespace='##targetNamespace'"
	 * @generated
	 */
	Revision getWasRevisionOf();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getWasRevisionOf <em>Was Revision Of</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Was Revision Of</em>' containment reference.
	 * @see #getWasRevisionOf()
	 * @generated
	 */
	void setWasRevisionOf(Revision value);

	/**
	 * Returns the value of the '<em><b>Was Started By</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Was Started By</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Was Started By</em>' containment reference.
	 * @see #setWasStartedBy(Start)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_WasStartedBy()
	 * @model containment="true" upper="-2" transient="true" volatile="true" derived="true"
	 *        extendedMetaData="kind='element' name='wasStartedBy' namespace='##targetNamespace'"
	 * @generated
	 */
	Start getWasStartedBy();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getWasStartedBy <em>Was Started By</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Was Started By</em>' containment reference.
	 * @see #getWasStartedBy()
	 * @generated
	 */
	void setWasStartedBy(Start value);

	/**
	 * Returns the value of the '<em><b>Id</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Id</em>' attribute isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Id</em>' attribute.
	 * @see #setId(String)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_Id()
	 * @model extendedMetaData="kind='attribute' name='id' namespace='##targetNamespace'"
	 * @generated
	 */
	String getId();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getId <em>Id</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Id</em>' attribute.
	 * @see #getId()
	 * @generated
	 */
	void setId(String value);

	/**
	 * Returns the value of the '<em><b>Ref</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Ref</em>' attribute isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Ref</em>' attribute.
	 * @see #setRef(QName)
	 * @see xtendCode.prov.ProvPackage#getDocumentRoot_Ref()
	 * @model dataType="org.eclipse.emf.ecore.xml.type.QName"
	 *        extendedMetaData="kind='attribute' name='ref' namespace='##targetNamespace'"
	 * @generated
	 */
	QName getRef();

	/**
	 * Sets the value of the '{@link xtendCode.prov.DocumentRoot#getRef <em>Ref</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Ref</em>' attribute.
	 * @see #getRef()
	 * @generated
	 */
	void setRef(QName value);

} // DocumentRoot
